###########################################################
### Welcome to Beautiful Jekyll!
### Customized for Xiao Huang
###########################################################

############################
# --- Required options --- #
############################

# Name of website
title: Xiao Huang

# Your name to show in the footer
author:

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  About Me: "about"
  Research: "research"
  Publications: "publications"
  CV: "cv"
  Contact: "contact"

################
# --- Logo --- #
################

avatar: "/assets/img/avatar-icon.png"
round-avatar: true

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  email: "xh_eco@outlook.com"
  ORCID: "0009-0000-4762-8864"
  ResearchGate: "Xiao-Huang-28"
  rss: false

###########################
# --- General options --- #
###########################

share-links-active:
  twitter: true
  facebook: true
  linkedin: true

url-pretty: "XiaoHuang.com"
title-on-all-pages: true
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: true
navbar-var-length: false

######################################
# --- Colours / background image --- #
######################################

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

#################################
# --- Web Analytics Section --- #
#################################

#gtag: "G-XXXXXXXXXX"
#cloudflare_analytics: ""
#gtm: ""
#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

####################
# --- Comments --- #
####################

#disqus: ""
#fb_comment_id: ""
#commentbox: ""
#utterances:
#  repository: ""
#  issue-term: title
#  theme: github-light
#  label: blog-comments

################
# --- Misc --- #
################

date_format: "%B %-d, %Y"

#################################################################################
# --- You don't need to touch anything below here --- #
#################################################################################

timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
